### PR TITLE
Multi-tenancy support

### PR DESCRIPTION
**Pull request by qbalin**
Hi James!

I made a few modifications I'd be happy to discuss with you.

I managed to authenticate a user outside of our tenancy, that was hard because the info was buried deep into Microsoft's terrible doc, but the changes to make it work are ridiculous, I let you see by yourself.

So, with a properly configured app in the AzureAD portal, the changes allow to authenticate users from in and outside the tenancy.

Now I'm wondering if an app that's not configured for multi-tenancy would work with those changes, I haven't tested yet (I'm just thinking about it). If not I guess that can be done by passing an argument to the client-side function.

Tell me what you think, but before, have a nice weekend!

Quentin

### CODE REVIEW

**Comment by djluck** [comment]
Quentin,

This is great stuff, where abouts in the docs did you find these urls? I'll test it tomorrow and merge it in then.

James

**Comment by qbalin** [comment]
Hi James, 

Sure, here are the references:
- a question I asked in stackoverflow: http://stackoverflow.com/questions/30787698/oauth-ing-users-not-belonging-to-my-azuread-tenancy/30789019#30789019
- I read this many times without realizing the answer for multi-tenancy was used a bunch of times (the word "common" appear everywhere): https://msdn.microsoft.com/en-US/library/azure/dn645542.aspx
- And this is where I found that the equivalent to the "common" keyword in the Graph API is "my organization": https://msdn.microsoft.com/en-us/library/azure/dn424880.aspx

I was worried that using those keywords would not allow to use your package in a single-tenant app. I turned multi-tenancy off in AzureAD, and the user that were able to connect are still able to connect (even the one outside the tenancy), which is the behavior expected: when switching to off, AzureAD clearly -for once- says that any user already signed in will still be able to connect to the app. So it seems that my modification did not break anything in this case. I wanted to do more testing, like trying your package with an app that never was configured for multi-tenancy, but I did not have time to do it so far.

Tell me if you need any other reference or anything that could help.

Quentin

**Comment by djluck** [comment]
Sorry for the delay Quentin, it's been a busy week at work. Merging this in now and I'll be updating the meteor packages.

**Comment by qbalin** [comment]
Awesome! No problem, it's been pretty busy here too. Thanks a lot!

**Pull request merged**
